<a href="https://colab.research.google.com/github/rSith/machine-learning-specialization/blob/main/ML_Specialization_02_Multiple_Variable_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mutiple Variable Linear Regression
> Expands on simple lnear regression by adding more independent variables.

## Goals
> - Extend data structures to support multiple features
> - Rewrite prediction, cost and gradient routines to support multiple features
> - Utiliza NumPy `np.dot` to vectoriza their implementations for speed and simplicity

### Tools
- NumPy : for Scientific computing
- Matplotlib : for plotting data
- copy : Creates a shallow copy of an object
- math : Provides access to standard mathematical constants and functions

In [3]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(precision=2)     #reduced display precision on numpy arrays

## Problem Statement
> **Housing price prediction**: The training dataset contains 3 examples with four features( size, bedroom, floors and, age )

In [4]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

### Matrix X contain Examples
Our examples(X values and Y values) are stored in a NumPy matrix X_train. Each row of the matrix represents one example.
> When we have $m$ training examples and there are $n$ features, $X$ is a matrix with dimensions $(m, n)$ *(in our problem $m=3$, $n=4$)*

Display the input data :

In [5]:
# data is stored in numpy array/matrix
print(f"X Shape: {X_train.shape}, X  Type:{type(X_train)}")
print(X_train)
print(f"y Shape: {y_train.shape}, y Type:{type(y_train)}")
print(y_train)

X Shape: (3, 4), X  Type:<class 'numpy.ndarray'>
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y Shape: (3,), y Type:<class 'numpy.ndarray'>
[460 232 178]


### Parameter vector w, b
> w is a vector with $n$ elements.
- Each element contains the parameter associated with one feature.
- in our dataset $n=4$

> b is a scalar parameter

For demonstration, $w$ and $b$ will be initial selected values that are near the optimal. $w$ is a 1-D NumPy vector

In [6]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>
